// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOK60AqqTn6OsUHUdfarDDCf2U7xDbJ5w',
    appId: '1:150756103756:web:ac5f7f742d8ef5771fc6e9',
    messagingSenderId: '150756103756',
    projectId: 'projeto-eb081',
    authDomain: 'projeto-eb081.firebaseapp.com',
    storageBucket: 'projeto-eb081.appspot.com',
    measurementId: 'G-5SNTH8BBL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC86zSMEJBFNNSJLqZIPvpKRkHuScsbKf0',
    appId: '1:150756103756:android:acc279ddc74c8b581fc6e9',
    messagingSenderId: '150756103756',
    projectId: 'projeto-eb081',
    storageBucket: 'projeto-eb081.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUytW5QY6NV-nGUquUPEMw91MujjKxbqM',
    appId: '1:150756103756:ios:781404ee6d367d071fc6e9',
    messagingSenderId: '150756103756',
    projectId: 'projeto-eb081',
    storageBucket: 'projeto-eb081.appspot.com',
    iosClientId: '150756103756-9b3s2ac2b70mhpn6lcu5p91u4oj9n6bk.apps.googleusercontent.com',
    iosBundleId: 'com.example.projeto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUytW5QY6NV-nGUquUPEMw91MujjKxbqM',
    appId: '1:150756103756:ios:781404ee6d367d071fc6e9',
    messagingSenderId: '150756103756',
    projectId: 'projeto-eb081',
    storageBucket: 'projeto-eb081.appspot.com',
    iosClientId: '150756103756-9b3s2ac2b70mhpn6lcu5p91u4oj9n6bk.apps.googleusercontent.com',
    iosBundleId: 'com.example.projeto',
  );
}
